# Generated by Django 4.2.2 on 2023-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
