# Generated by Django 4.2.2 on 2023-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20)),
                ('Body', models.TextField()),
                ('Priority', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=11)),
            ],
        ),
    ]
