# Generated by Django 4.2.2 on 2023-07-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=20)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_Update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
