# Generated by Django 4.2.2 on 2023-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
